parameters:
  vel:
    min: 0.0
    max: 1.0
    n: 4
  horz_angle:
    - -5.0
    - 0.0
    - 5.0
input_map:
  current_vel: vel
  horizontal_angle: horz_angle
output_dir: ../results/samples
use_monte_carlo: false
