parameters:
  vel:
    min: 0.0
    max: 1.0
    n: 4
  horz_angle:
    min: -5.0
    max: 5.0
    n: 4
input_map:
  current_vel: vel
  horizontal_angle: horz_angle
output_dir: ../results/monte_carlo
use_monte_carlo: true
